language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
  licenses:
    - '.+'
script:
    - ./gradlew assembleFreeRelease
