language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - build-tools-19.1.0
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
  licenses:
    - '.+'
script:
    - ./gradlew assembleFreeRelease
